services:
  squid:
    image: squid-minimal-q:1.2
    
    container_name: squid-proxy
    
    restart: unless-stopped
    
    volumes:
      # Configuration files
      - ./config:/etc/squid:rw
      
      # Kerberos configuration
      - ./config/krb5.conf:/etc/krb5.conf:ro
      
      # Logs (persistent, readable by external programs)
      - ./logs:/var/log/squid
      
      # Cache (persistent, readable by external programs) 
      - ./cache:/var/cache/squid
      
      # Timezone data for Asia/Qyzylorda
      - /etc/localtime:/etc/localtime:ro
      
    environment:
      - TZ=Asia/Qyzylorda
      - KRB5_CONFIG=/etc/krb5.conf
      - KRB5_KTNAME=/etc/squid/squid.keytab

    #deploy:
    #  resources:
    #    limits:
    #      cpus: "2.0"         # максимум 2 ядра
    #      memory: 2G          # максимум 2 гигабайта оперативки
    #    reservations:
    #      cpus: "0.5"         # резервируем 0.5 CPU
    #      memory: 512M        # гарантированный минимум памяти
    
    # Logging configuration with rotation
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Use macvlan for direct network access (required for AD authentication)
    networks:
      squid-macvlan:
        ipv4_address: 192.168.10.22
    #dns:
    #  - 192.168.10.2
    #  - 192.168.10.7   

networks:
  squid-macvlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.10.0/23
          gateway: 192.168.10.1
          ip_range: 192.168.10.22/32
