---
services:
  squid-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: squid-proxy
    ports:
      - "8078:3128"
      - "8077:3129"
    volumes:
      - ./config:/etc/squid
      - ./cache:/var/spool/squid
      - ./logs:/var/log/squid
    environment:
      - TZ=Asia/Qyzylorda
    restart: unless-stopped
    networks:
      - squid-net

networks:
  squid-net:
    driver: bridge
